### ISSUE TITLE
NoClassDefFoundError thrown on Android 7 or lower

### ISSUE THREAD

**Issue by ubaierbhat** [elastic/apm-agent-android#241]
The sdk crashes the app in initilization on devices running Android 7 or lower 

version: `0.11.0`

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
       at io.opentelemetry.exporter.sender.okhttp.internal.OkHttpGrpcSender.<init>(OkHttpGrpcSender.java:82)
       at io.opentelemetry.exporter.sender.okhttp.internal.OkHttpGrpcSenderProvider.createSender(OkHttpGrpcSenderProvider.java:43)
       at io.opentelemetry.exporter.internal.grpc.GrpcExporterBuilder.build(GrpcExporterBuilder.java:158)
       at io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporterBuilder.build(OtlpGrpcMetricExporterBuilder.java:227)
       at co.elastic.apm.android.sdk.connectivity.opentelemetry.DefaultSignalConfiguration.getOtlpGrpcMetricExporter(DefaultSignalConfiguration.java:115)
       at co.elastic.apm.android.sdk.connectivity.opentelemetry.DefaultSignalConfiguration.provideMetricExporter(DefaultSignalConfiguration.java:81)
       at co.elastic.apm.android.sdk.connectivity.opentelemetry.base.BaseSignalConfiguration.getMetricReader(BaseSignalConfiguration.java:46)
       at co.elastic.apm.android.sdk.ElasticApmAgent.getMeterProvider(ElasticApmAgent.java:331)
       at co.elastic.apm.android.sdk.ElasticApmAgent.initializeOpentelemetry(ElasticApmAgent.java:233)
       at co.elastic.apm.android.sdk.ElasticApmAgent.onInitializationFinished(ElasticApmAgent.java:172)
       at co.elastic.apm.android.sdk.ElasticApmAgent.initialize(ElasticApmAgent.java:124)
```

**Comment by LikeTheSalad** [comment]
Hi @ubaierbhat 

This can be avoided by adding Java 8 desugaring support to your project. More info [here](https://www.elastic.co/guide/en/apm/agent/android/current/setup.html#minsdk-24-support).
