### ISSUE TITLE
The app is crashing during runtime with a ClassNotFoundException

### ISSUE THREAD

**Issue by agap** [elastic/apm-agent-android#296]
I'm evaluating Elastic APM Agent for our Android mobile app and the issue I'm struggling with now is that the app seems to be crashing upon the start with the following exception:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lco/elastic/apm/android/sdk/instrumentation/CoroutineExtensionsKt;
    at com.sample.ui.home.HomeActivity.onCreate(HomeActivity.kt:85)
    at android.app.Activity.performCreate(Activity.java:8540)
    at android.app.Activity.performCreate(Activity.java:8504)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:211)
    at android.os.Looper.loop(Looper.java:300)
    at android.app.ActivityThread.main(ActivityThread.java:8410)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.ClassNotFoundException: Didn't find class "co.elastic.apm.android.sdk.instrumentation.CoroutineExtensionsKt" on path: DexPathList[[zip file "/data/app/~~8aRlakVCn29H9UaOEqT17g==/com.sample-PQGa7PVmHZmrBednHFltAA==/base.apk"],nativeLibraryDirectories=[/data/app/~~8aRlakVCn29H9UaOEqT17g==/com.sample-PQGa7PVmHZmrBednHFltAA==/lib/arm64, /data/app/~~8aRlakVCn29H9UaOEqT17g==/com.sample-PQGa7PVmHZmrBednHFltAA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at com.sample.ui.home.HomeActivity.onCreate(HomeActivity.kt:85) 
    at android.app.Activity.performCreate(Activity.java:8540) 
    at android.app.Activity.performCreate(Activity.java:8504) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1440) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3890) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062) 
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loopOnce(Looper.java:211) 
    at android.os.Looper.loop(Looper.java:300) 
    at android.app.ActivityThread.main(ActivityThread.java:8410) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 
```

Is it something that is well-known? How can we address it?

Thanks in advance,
Artem

**Comment by LikeTheSalad** [comment]
Hi @agap 

Thank you for your feedback. It's not a known issue at the moment, though based on your logs, it seems like your project might be missing this dependency: https://central.sonatype.com/artifact/co.elastic.apm/android-sdk-ktx/0.16.0

It should be automatically added there if you're using our [Gradle plugin](https://plugins.gradle.org/plugin/co.elastic.apm.android), unless there's a problem with it. Would you mind confirming what version are you using and if you're setting the agent up via [our Gradle plugin](https://www.elastic.co/guide/en/apm/agent/android/current/setup.html#adding-gradle-plugin) or [doing so manually](https://www.elastic.co/guide/en/apm/agent/android/current/setup.html#manual-setup) instead?

Thank you.

**Comment by agap** [comment]
Hi @LikeTheSalad !

I've tried version 0.15 and 0.16. The plugin is added to the project's root `build.gradle` file and then it applied to the app module's `build.gradle` file (we have a multi-module app, so I applied it only to the application file). I'll try to add that dependency manually.

**Comment by agap** [comment]
Sorry that I wasn't answering for almost two weeks as I was OOO

So I tried setting it up manually, and it still fails with the following error:

```
Caused by: java.io.FileNotFoundException: co_elastic_apm_android.properties
       at android.content.res.AssetManager.nativeOpenAsset(Native Method)
       at android.content.res.AssetManager.open(AssetManager.java:914)
       at android.content.res.AssetManager.open(AssetManager.java:891)
       at co.elastic.apm.android.sdk.internal.services.metadata.ApmMetadataService.getApmInfoProperties(ApmMetadataService.java:87)
       at co.elastic.apm.android.sdk.internal.services.metadata.ApmMetadataService.lambda$new$0$co-elastic-apm-android-sdk-internal-services-metadata-ApmMetadataService(ApmMetadataService.java:38) 
       at co.elastic.apm.android.sdk.internal.services.metadata.ApmMetadataService$$ExternalSyntheticLambda0.get(Unknown Source:4) 
       at co.elastic.apm.android.sdk.internal.utilities.providers.LazyProvider.get(LazyProvider.java:32) 
       at co.elastic.apm.android.sdk.internal.services.metadata.ApmMetadataService.getDeploymentEnvironment(ApmMetadataService.java:68) 
       at co.elastic.apm.android.sdk.internal.configuration.impl.GeneralConfiguration.getServiceEnvironment(GeneralConfiguration.java:49) 
       at co.elastic.apm.android.sdk.attributes.resources.ServiceIdVisitor.visit(ServiceIdVisitor.java:39) 
       at co.elastic.apm.android.sdk.attributes.impl.ComposeAttributesVisitor.visit(ComposeAttributesVisitor.java:36) 
       at co.elastic.apm.android.sdk.attributes.impl.VisitorAttributesCreator.create(VisitorAttributesCreator.java:36) 
       at co.elastic.apm.android.sdk.ElasticApmAgent.initializeOpentelemetry(ElasticApmAgent.java:279) 
       at co.elastic.apm.android.sdk.ElasticApmAgent.onInitializationFinished(ElasticApmAgent.java:226) 
       at co.elastic.apm.android.sdk.ElasticApmAgent.initialize(ElasticApmAgent.java:178) 
       at co.elastic.apm.android.sdk.ElasticApmAgent.initialize(ElasticApmAgent.java:164) 
       at com.truckspy.truckspy.TruckSpyApplication.onCreate(TruckSpyApplication.kt:80) 
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1289) 
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7241) 
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241) 
       at android.os.Handler.dispatchMessage(Handler.java:106) 
       at android.os.Looper.loopOnce(Looper.java:211) 
       at android.os.Looper.loop(Looper.java:300) 
       at android.app.ActivityThread.main(ActivityThread.java:8410) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 
```

I double- and triple-checked that the Elastic's Gradle plugin is no longer applied in project's root build.gradle file or the app module's build.gradle file, and there is nothing that would point to that plugin being used. But the crash still happens in the application's `onCreate` method, in the following call of Elastic's API:

```kotlin
        ElasticApmAgent.initialize(
            this,
            configuration,
            Connectivity.withApiKey(BuildConfig.ELASTIC_SERVER, BuildConfig.ELASTIC_TOKEN)
        )
```

**Comment by LikeTheSalad** [comment]
Hi @agap 

It seems like the "deployment environment" config parameter is not found. Please make sure you set the following config params when defining your configuration:

```java
ElasticApmConfiguration configuration = ElasticApmConfiguration.builder()
        .setServiceName("App Name")
        .setServiceVersion("1.0.0")
        .setDeploymentEnvironment("debug")
        .build();

ElasticApmAgent.initialize(
            this,
            configuration,
            Connectivity.withApiKey(BuildConfig.ELASTIC_SERVER, BuildConfig.ELASTIC_TOKEN)
        );

```

**Comment by agap** [comment]
Oh, seems to work now. Thanks for the help, @LikeTheSalad, much appreciated !

**Comment by LikeTheSalad** [comment]
Great news! 🙌  It seems like we can close this issue for now, though feel free to reopen it if you bump into the same problem again.

Thank you.
