### ISSUE TITLE
not receiving Data at elastic Side

### ISSUE THREAD

**Issue by ahmedhkhalil** [elastic/apm-agent-android#318]
Dears,
we are trying to instrument flutter application using andorid sdk native agent from Elastic we have followed below documentation 
https://www.elastic.co/observability-labs/blog/monitoring-android-applications-apm 
there is no data appeared on elastic side despite below : 
on Android Side we are receiving below warning:
D/ELASTIC_AGENT(19073): Ignoring central config sync request
I/ELASTIC_AGENT(19073): Central config returned max age is null
I/ELASTIC_AGENT(19073): Scheduling next central config poll
D/ELASTIC_AGENT(19073): Next central config poll in 60 seconds
D/ELASTIC_AGENT(19073): Starting span: 'SdkSpan{traceId=e08badad1310d7d54bfb90c72ddd7a82, spanId=a87fee2a479b8368, parentSpanContext=ImmutableSpanContext{traceId=e08badad1310d7d54bfb90c72ddd7a82, spanId=0de1adc07d3f86e1, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, name=Paused, kind=INTERNAL, attributes=AttributesMap{data={network.carrier.icc=eg, [session.id](http://session.id/)=802fa057-7ba2-4c1f-9146-dcc37aecdf4e, network.carrier.mcc=602, network.connection.type=wifi, type=mobile, [network.carrier.name](http://network.carrier.name/)=Orange EG, network.carrier.mnc=01, fragmentName=FlutterFragment}, capacity=128, totalAddedValues=9}, status=ImmutableStatusData{statusCode=OK, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1716282098617757968, endEpochNanos=0}', within context: '{opentelemetry-trace-span-key=SdkSpan{traceId=e08badad1310d7d54bfb90c72ddd7a82, spanId=0de1adc07d3f86e1, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, name=Paused, kind=INTERNAL, attributes=AttributesMap{data={network.carrier.icc=eg, activityName=MainActivity, [session.id](http://session.id/)=802fa057-7ba2-4c1f-9146-dcc37aecdf4e, network.carrier.mcc=602, network.connection.type=wifi, type=mobile, [network.carrier.name](http://network.carrier.name/)=Orange EG, network.carrier.mnc=01, [screen.name](http://screen.name/)=MainActivity}, capacity=128, totalAddedValues=11}, status=ImmutableStatusData{statusCode=OK, description=}, totalRecordedEvents=2, totalRecordedLinks=0, startEpochNanos=1716282098614000000, endEpochNanos=0}}'

and on Elastic APM fleet Server i recieve below : 
./elastic-agent-20240429-336.ndjson:{"log.level":"info","@timestamp":"2024-04-29T13:17:36.477Z","message":"request ok","component":{"binary":"apm-server","dataset":"elastic_
agent.apm_server","id":"apm-default","type":"apm"},"log":{"source":"apm-default"},"url.original":"/","http.request.method":"POST","user_agent.original":"OTel-OTLP-Exporter-J
ava/1.34.1","http.request.id":"f4c43c38-86f1-4750-928e-cfb726ab38ea","log.origin":{"file.line":62,"file.name":"middleware/log_middleware.go","function":"[github.com/elastic/a](http://github.com/elastic/a)
pm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1"},"log.logger":"request","source.address":"","event.duration":66983,"http.request.body.bytes":
804,"http.response.status_code":200,"ecs.version":"1.6.0","service.name":"apm-server","ecs.version":"1.6.0"}

{"log.level":"info","@timestamp":"2024-05-21T09:58:24.366Z","message":"not modified","component":{"binary":"apm-server","dataset":"elastic_agent.apm_server","id":"apm-default","type":"apm"},"log":{"source":"apm-default"},"url.original":"/config/v1/agents?service.name=####&service.environment=######","log.origin":{"file.line":62,"file.name":"middleware/log_middleware.go","function":"github.com/elastic/apm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1"},"service.name":"apm-server","http.request.body.bytes":0,"http.response.status_code":304,"user_agent.original":"Dalvik/2.1.0 (Linux; U; Android 14; SM-S918B Build/UP1A.231005.007)","http.request.id":"13f77e5b-4f72-44b1-9c9a-dc23757123dd","event.duration":61349,"log.logger":"request","http.request.method":"GET","source.address":"197.38.152.50","ecs.version":"1.6.0","ecs.version":"1.6.0"}

Despite that no data shown in elastic or kibana and service not appeared

**Comment by LikeTheSalad** [comment]
Got it, although it's still confusing because, apart from the removed `service.name` and `environment.name` attrs, there are some other missing attrs that we send from the Android agent, such as `network.connection.type`, or `activityName`, which, even though both show up in the logs that you've shared from your application, it seems like those are missing from the server logs, which is why I'm wondering if maybe the logs that you are seeing in your server might come from a different source rather than the Elastic Android agent.

It would be helpful to confirm that the server endpoint/auth values are the ones that show up in Kibana, as per my instructions above, just to discard that it might not be that kind of issue. Also, could you confirm which version of the Elastic Stack are you using? That could help to narrow down the possible causes of this issue.

**Comment by ahmedhkhalil** [comment]
yes i confirm that , server url is correct and i am not using auth token in my environment , my elastic version is latest 8.13.4

**Comment by LikeTheSalad** [comment]
Thank you for confirming. If that's the case, then it doesn't look like there are too many possible causes for this issue, at least on the Elastic agent configuration side of things. Having said that, I'd like to confirm a couple of things, does your APM Server URL starts with `http` or `https`? And, have you added any configuration changes into your app regarding the export protocol, as explained [here](https://www.elastic.co/guide/en/apm/agent/android/current/configuration.html#server-export-protocol)?

**Comment by ahmedhkhalil** [comment]
APM endpoint is HTTP but Public URL is behind proxy which make ssl temination for requests from https to http 
yes i changed endpoint from otel to http as below 
private val apmConfiguration: ElasticApmConfiguration = ElasticApmConfiguration.builder()
    .setExportProtocol(ExportProtocol.HTTP)
    .setLibraryLoggingPolicy(LoggingPolicy.enabled(LogLevel.DEBUG))
    .setServiceName("Availo-Test-mum")
    .setServiceVersion("1.0.4")
    .setDeploymentEnvironment(deploymentEnvironment)
    .build()

**Comment by LikeTheSalad** [comment]
Thank you.

Usually, requests to endpoints starting with `http://` tend to have issues due to Android's SSL/TLS default config. For testing purposes, I'd recommend enabling cleartext traffic, as explained [here](https://www.elastic.co/guide/en/apm/agent/android/current/faq.html#faq-ssl-debug), just to discard that we're not dealing with an SSL/TLS related issue.

**Comment by ahmedhkhalil** [comment]
in android endpoint is https not http , as android refuse to send requests to http
ok when i enabling clear text what do you like me to capture

**Comment by LikeTheSalad** [comment]
Hi @ahmedhkhalil - Thank you for your patience. I just checked and it seems like there's an issue in our APM Server when using HTTP to export Android telemetry. I'm currently taking a look into it to gather more details, though, in the meantime, if you switch to `ExportProtocol.GRPC`, you should be able to see your Android APM data in Kibana.

I'll keep adding updates here as soon as I can find more info on the issue with HTTP.

**Comment by ahmedhkhalil** [comment]
hi @LikeTheSalad when we tried grpc we was reciving below error message 
E/ELASTIC_AGENT( 9960): java.io.IOException: unexpected end of stream on com.android.okhttp.Address@e77c591c
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:211)
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderField(DelegatingHttpsURLConnection.java:191)
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:30)
E/ELASTIC_AGENT( 9960):     at co.elastic.apm.android.sdk.internal.features.centralconfig.fetcher.CentralConfigurationFetcher.fetch(CentralConfigurationFetcher.java:78)
E/ELASTIC_AGENT( 9960):     at co.elastic.apm.android.sdk.internal.features.centralconfig.CentralConfigurationManager.sync(CentralConfigurationManager.java:80)
E/ELASTIC_AGENT( 9960):     at co.elastic.apm.android.sdk.internal.features.centralconfig.poll.ConfigurationPollManager.onTaskRun(ConfigurationPollManager.java:67)
E/ELASTIC_AGENT( 9960):     at co.elastic.apm.android.sdk.internal.services.periodicwork.ManagedPeriodicTask.runTask(ManagedPeriodicTask.java:37)
E/ELASTIC_AGENT( 9960):     at co.elastic.apm.android.sdk.internal.services.periodicwork.PeriodicWorkService.run(PeriodicWorkService.java:90)
E/ELASTIC_AGENT( 9960):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
E/ELASTIC_AGENT( 9960):     at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/ELASTIC_AGENT( 9960):     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
E/ELASTIC_AGENT( 9960):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/ELASTIC_AGENT( 9960):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/ELASTIC_AGENT( 9960):     at java.lang.Thread.run(Thread.java:1012)
E/ELASTIC_AGENT( 9960): Caused by: java.io.EOFException: \n not found: size=0 content=...
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
E/ELASTIC_AGENT( 9960):     at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)

**Comment by LikeTheSalad** [comment]
It seems like those logs are related to central config polling, which is a separate request from the traces exporting one. Could you verify if you can see your app listed in Kibana -> Observability -> APM -> Services?

**Comment by ahmedhkhalil** [comment]
Dears,
i tried below setup with grpc 
APM local end point is http and it's public access without any load balancer in middle , i am able to recieve session and service appear in Kibana services tab 
but when ever i put haproxy in middle to make ssl termination and send traffic to backend either grpc or http , no data is received on elastic and response from apm server is 400 and error message "invalid character "
i suspect that there is issue from APM side 
![image](https://github.com/elastic/apm-agent-android/assets/95984434/849ed357-c04e-4ed5-86d3-64d4c8f27509)

**Comment by georgesamirmansour** [comment]
E/AndroidRuntime( 9291): java.lang.NoClassDefFoundError: Failed resolution of: Lio/opentelemetry/instrumentation/api/internal/SemconvStability;
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.api.instrumenter.http.HttpClientAttributesExtractorBuilder.buildNetExtractor(HttpClientAttributesExtractorBuilder.java:134)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.api.instrumenter.http.HttpClientAttributesExtractor.<init>(HttpClientAttributesExtractor.java:100)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.api.instrumenter.http.HttpClientAttributesExtractorBuilder.build(HttpClientAttributesExtractorBuilder.java:129)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.okhttp.v3_0.internal.OkHttpInstrumenterFactory.create(OkHttpInstrumenterFactory.java:56)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons.lambda$static$2(OkHttp3Singletons.java:35)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons.$r8$lambda$u63Q7IRr8X_9Th6yCeJtzlM1cyI(OkHttp3Singletons.java:0)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons$$ExternalSyntheticLambda0.get(R8$$SyntheticClass:0)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.CachedSupplier.get(CachedSupplier.java:31)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons.lambda$static$5(OkHttp3Singletons.java:83)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons.$r8$lambda$FBKUum8dYLg-qIeXrCw3rmWpOr8(OkHttp3Singletons.java:0)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons$$ExternalSyntheticLambda3.get(R8$$SyntheticClass:0)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.CachedSupplier.get(CachedSupplier.java:31)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.LazyInterceptor.intercept(LazyInterceptor.java:27)
E/AndroidRuntime( 9291):     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons.lambda$static$4(OkHttp3Singletons.java:76)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons.$r8$lambda$663SEQRE2c1G7-M_pfa4eU-NLQ4(OkHttp3Singletons.java:0)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons$$ExternalSyntheticLambda2.intercept(R8$$SyntheticClass:0)
E/AndroidRuntime( 9291):     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons.lambda$static$3(OkHttp3Singletons.java:65)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons.$r8$lambda$gJVQNJFg1SbPjywQG7gDltoRIL0(OkHttp3Singletons.java:0)
E/AndroidRuntime( 9291):     at io.opentelemetry.instrumentation.library.okhttp.v3_0.internal.OkHttp3Singletons$$ExternalSyntheticLambda1.intercept(R8$$SyntheticClass:0)
E/AndroidRuntime( 9291):     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/AndroidRuntime( 9291):     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
E/AndroidRuntime( 9291):     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
E/AndroidRuntime( 9291):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime( 9291):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime( 9291):     at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime( 9291): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.opentelemetry.instrumentation.api.internal.SemconvStability" on path: DexPathList[[zip file "/data/app/~~ytm5u3m8tCcFs9-hsUwAjQ==/app.t2.availo-1LyuzmDaaTFr8EbTXOK-Jg==/base.apk"],nativeLibraryDirectories=[/data/app/~~ytm5u3m8tCcFs9-hsUwAjQ==/app.t2.availo-1LyuzmDaaTFr8EbTXOK-Jg==/lib/arm64, /data/app/~~ytm5u3m8tCcFs9-hsUwAjQ==/app.t2.availo-1LyuzmDaaTFr8EbTXOK-Jg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 9291):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime( 9291):     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 9291):     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by ahmedhkhalil** [comment]
hi @LikeTheSalad above is commnet from my college show exception happening when we try to use new SDK v.18 that you just released

**Comment by LikeTheSalad** [comment]
> Dears, i tried below setup with grpc APM local end point is http and it's public access without any load balancer in middle , i am able to recieve session and service appear in Kibana services tab but when ever i put haproxy in middle to make ssl termination and send traffic to backend either grpc or http , no data is received on elastic and response from apm server is 400 and error message "invalid character " i suspect that there is issue from APM side ![image](https://private-user-images.githubusercontent.com/95984434/333271469-849ed357-c04e-4ed5-86d3-64d4c8f27509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTQyOTQsIm5iZiI6MTcxNjc5Mzk5NCwicGF0aCI6Ii85NTk4NDQzNC8zMzMyNzE0NjktODQ5ZWQzNTctYzA0ZS00ZWQ1LTg2ZDMtNjRkNGM4ZjI3NTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA3MTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOWRlN2U5ZmM1YTI4YWZiZmFjMGNjYzM0MTlkNjZmYjg0NmY5NDkzMWEzZDY2OWJhMmNjYjA0ZWVjNjdmN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.70GbajpIsvNZcbt-G2o3sWyh4vu7nemy-4k-exIDA7c)

Hi @ahmedhkhalil - It seems like there might be some issues with your HAProxy setup when communicating to the APM Server. The changes I've made in the new version `0.18.0` are only to fix the HTTP exporting, however, based on your message, it seems like this proxy issue is also happening when using HTTP as well, and it also seems like the Android agent exporting is working properly when there's no proxy set in between. Therefore, I'd suggest you would be to raise this issue in the [APM Server repo](https://github.com/elastic/apm-server/issues/new/choose) since they will be able to provide better support for APM Server-related queries.

**Comment by ahmedhkhalil** [comment]
@LikeTheSalad  issue her is that EUM   Data Is received successfully without any issue , as i mentioned issue may be on how Android Agent is sending data

**Comment by LikeTheSalad** [comment]
> @LikeTheSalad issue her is that EUM Data Is received successfully without any issue , as i mentioned issue may be on how Android Agent is sending data

Just to confirm, this is my understanding:

- Elastic Agent -> Server = works ✅
- Elastic Agent -> HAProxy -> Server = does not work ⛔️

Is that correct?

**Comment by ahmedhkhalil** [comment]
Elastic Agent -> Server = works ✅ yes but HTTP traffic only 
Elastic Agent -> HAProxy -> Server = does not work ⛔️ over https "from Agent to haproxy https and from haproxy to agent http"

**Comment by LikeTheSalad** [comment]
I see, thank you. So it seems like you're trying to connect to HAProxy over HTTPS. I think we can verify a couple of things to make sure what's going on:

- To discard issues with the protocol, I think it might be worth checking both GRPC and HTTP as export protocols from the agent, HTTP should work well starting from version `0.18.0` of the Elastic agent.
- If you're getting logs that contain the following error: `javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException` or any SSL/TLS related issue, then it seems like your HAProxy instance might not be using trusted CAs by the Android OS.

Those are the possible issues that come to my mind, although there might be specific HAProxy-related configs that I'm not aware of which could be causing other issues. In any case, I think it's worth checking the above items in detail to discard potential root causes. Please bear in mind that the SSL/TLS configuration used by the Elastic Agent is the same as the one provided within the Android OS and there's no custom SSL config provided by the Agent. If you happen to have SSL cert issues, you should take a look at [Android's official documentation](https://developer.android.com/privacy-and-security/security-ssl#CommonProblems) on how to address them.
