### ISSUE TITLE
Unable to create application uz.davrbank.mobile.App: java.lang.RuntimeException: expected SNTP time from last boot to be cached. couldn't find it.

### ISSUE THREAD

**Issue by YusufbekIbragimov** [elastic/apm-agent-android#339]
I found this error in my firebase console, i couldn't find any solution for this kind of error, please check your library for this error. I leave all details of error:
    ```
Caused by java.lang.RuntimeException: expected SNTP time from last boot to be cached. couldn't find it.
       at co.elastic.apm.android.truetime.TrueTime._getCachedSntpTime(TrueTime.java:35)
       at co.elastic.apm.android.truetime.TrueTime.now(TrueTime.java:7)
       at co.elastic.apm.android.sdk.internal.time.ntp.TrueTimeWrapper.now(TrueTimeWrapper.java:1)
       at co.elastic.apm.android.sdk.internal.opentelemetry.tools.ElasticClock.now(ElasticClock.java:20)
       at io.opentelemetry.sdk.metrics.SdkMeterProvider.<init>(SdkMeterProvider.java:11)
       at io.opentelemetry.sdk.metrics.SdkMeterProviderBuilder.build(SdkMeterProviderBuilder.java:15)
       at io.opentelemetry.android.OpenTelemetryRumBuilder.buildMeterProvider(OpenTelemetryRumBuilder.java:35)
       at io.opentelemetry.android.OpenTelemetryRumBuilder.build(OpenTelemetryRumBuilder.java:76)
       at co.elastic.apm.android.sdk.ElasticApmAgent.initializeOpentelemetry(ElasticApmAgent.java:102)
       at co.elastic.apm.android.sdk.ElasticApmAgent.onInitializationFinished(ElasticApmAgent.java:10)
       at co.elastic.apm.android.sdk.ElasticApmAgent.initialize(ElasticApmAgent.java:3)
       at co.elastic.apm.android.sdk.ElasticApmAgent.initialize(ElasticApmAgent.java:2)
       at co.elastic.apm.android.sdk.ElasticApmAgent.initialize(ElasticApmAgent.java:1)
       at uz.davrbank.mobile.App.onCreate(App.kt:13)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7535)
       at android.app.ActivityThread.access$1500(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2158)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
Device
Brand:Samsung
Model:Galaxy S10 5G
Orientation:Portrait
RAM free: 2.76 GB
Disk free: 186.15 GB
Operating System
Version:Android 11
Orientation:Portrait
Rooted: No
Crash
Date:Jul 24, 2024, 10:41:20 AM
App version:1.0.3 (35)
```[tasklist]
### Tasks
```

**Comment by YusufbekIbragimov** [comment]
Hi @LikeTheSalad, thanks for your attention, is there will be a new release?

**Comment by LikeTheSalad** [comment]
I'll close this issue for now, feel free to reopen it in case the problem persists with the new version.

**Comment by YusufbekIbragimov** [comment]
Hi @LikeTheSalad, thanks for new version.
